### ISSUE TITLE
copy into svn

### ISSUE THREAD

**Issue by linas** [jkalbhenn/guile-dbd-sqlite3#4]
FYI,

I needed to create new versions for guile-dbi (misc patches) and bumped the version to 2.1.6.

I copied most of what was here into the gna.org svn repo, and bumped the version number to 2.1.6 just to be consistent.  I should have tarballs ready in a few hours, if all goes well.  FYI, I consider this github version to be the master version, and, for right now, am keeping the gna.org version in sync, manually.

**Comment by jkalbhenn** [comment]
thank you. i saw this late because github did not notify and sorry for not responding.
